### ISSUE TITLE
Songs don't showing on fast selectiom

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [revanced-apks/build-apps#29]
**Describe the bug**
I just entered on the app today and those didn't showed up
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20230318-103735](https://user-images.githubusercontent.com/86683930/226115797-9c381602-642d-437d-9dcf-7851b0e3aa22.jpg)

**Smartphone (please complete the following information):**
 - Device: samsung galaxy A12
 - OS: android 12

**Additional context**
**DO NOT REPORT REVANCED BUGS IN THIS REPO**

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
