### ISSUE TITLE
Cannot scroll through tracks or be able to turn off shuffle. 

### ISSUE THREAD

**Issue by brokenshardsofdeath** [revanced-apks/build-apps#30]
I have gone through the 5 previous releases for Revanced Spotify APK, and none of them contain the ability to scroll or being able to turn off shuffle.

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
