### ISSUE TITLE
When a song finish the app crash

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [revanced-apks/build-apps#32]
**Describe the bug**
When a song finishes and the app try to play the next song it crashes

**To Reproduce**
1. Play the song
2. Wait till the end
3. The app try to go to the next song
4. The app crashes

**Expected behavior**
The app plays the song normally

**Screenshots**
https://imgur.com/a/MTlW7Ij

**Smartphone (please complete the following information):**
 - Device: samsung galaxy a12
 - OS: android 12

**Comment by soyDESKTOP68A2MRFT** [comment]
The app is in it's last version (5.50.52)

**Comment by soyDESKTOP68A2MRFT** [comment]
I made a fast forward to don't make the screen recording so long

**Comment by Armagedon13** [comment]
Yes, it happens to me too, when the song finish or skip a song it crash.
Android 12 arm64
Motorola edge 30 pro

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
