### ISSUE TITLE
Login feature not working properly 

### ISSUE THREAD

**Issue by SadSatanSama** [revanced-apks/build-apps#33]
Signing in with Facebook and Google isn't working on Spotify revanced v. 8.8.28.409

1. Go to Spotify revanced 
2. Click on 'continue with Google/Facebook '
4. See error (login failed/something went wrong)

Expected behaviour:
Prompt to sign in page where I can sign in using Google/Facebook account 

**Screenshots**
![Screenshot_20230503-085816_Spotify](https://user-images.githubusercontent.com/37984514/235827818-31c28e25-40aa-4a7d-89ce-da5e161a91ca.png)
![Screenshot_20230503-085545_Facebook](https://user-images.githubusercontent.com/37984514/235827821-fd3460d3-32e4-4a37-8c97-87d358d3a9f9.png)

 - Device: Realme 7 Pro
 - OS: project elixir 3.7 (Android 13)

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
