### ISSUE TITLE
Youtube dislike error message when watching videos in playlists

### ISSUE THREAD

**Issue by UnknownUserZ** [revanced-apks/build-apps#36]
Hello, I have the newest version of the built youtube revanced. I have a problem when playing videos from my playlist, it keeps showing ReturnYoutubeDislikePatch:setOldUILayoutDislikes failure. I have the old version of revanced which is revanced 18.15.40 which does not have this issue. It gets really annoying when you see it when you have something playing in a playlist.

Thanks for reading this - A Revanced User
![Screenshot_20230507-205011](https://user-images.githubusercontent.com/99452572/236729966-6e63f13d-bf7d-42f2-9a89-26762185e4f9.jpg)

**Comment by Bluntedwarrior** [comment]
I get the same error

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
