### ISSUE TITLE
Messenger won't install with Facebook revanced

### ISSUE THREAD

**Issue by LouKingGood** [revanced-apks/build-apps#37]

**Comment by abuser895** [comment]
Install zarchive, and install your apk from there.

**Comment by takobaba** [comment]
Can someone explain how to, there is an app something called "zarchiver" not zarchive.

Also which facebook package are you installed to have both fb and messenger?

**Comment by abuser895** [comment]
Zarchiver you can dload it on playstore and install apk from there.

**Comment by takobaba** [comment]
Thanks abuser

The facebook apk I download from releases section doesnt seem to have messenger. Am I doing it wrong?

**Comment by james28909** [comment]
I also cannot install revanced manager, even if i try to use zarchiver. On my note 9 n960u zarchiver just uses the built in package installer. I also tried to download apk manager and try to install it but it still won't install. If i delete Facebook, it will install. But then after messenger is installedi cannot reinstall Facebook.

Any suggestions or insight would be helpful

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
