### ISSUE TITLE
Seekbar thumbnail doesnt shown in new version of youtube revanced extended

### ISSUE THREAD

**Issue by FarhanGz** [revanced-apks/build-apps#49]
**Describe the bug**
When i tap or swipe the seekbar, the mini thumbnail doesnt show

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12
![IMG_20230721_114346](https://github.com/revanced-apks/build-apps/assets/140139460/0ccd6638-5afa-4852-a10d-09c8632680f7)

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
