### ISSUE TITLE
Where is the Revanced setting on Twitter/X?

### ISSUE THREAD

**Issue by Salva-C** [revanced-apks/build-apps#50]
Sorry, but I can't find it.

**Comment by rabilrbl** [comment]
Please ask the community below.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.
Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
