### ISSUE TITLE
[BUG] SEARCHED YOUTUBE VIDEO NOT PLAYING AFTER 1:30 MINUTE

### ISSUE THREAD

**Issue by anubhavmauryaph** [revanced-apks/build-apps#57]
search video not playing only 1:30 duration video play. Video stuck after 1:30

![Screenshot_20230815-132104](https://github.com/revanced-apks/build-apps/assets/130752756/894f98d9-ef91-4d11-b608-24934231d9df)

**Comment by Scipply** [comment]
for me it is at 1:10 or 1:09(Im using an older version)
this is probably because the servers wont give you the rest of the video until you watch the ad that gets hiden by yt
strangely enough, I can watch yt on pc with the origin adblocker beyond 1:10

I hope someone finds an exploit or something to bypass this somehow without downloading the video or parts of it bcus it would take longer just to start the video
(Im not an expert in this and I have no idea if what I said is true; everything I said is like an opinion)

**Comment by Chris-Musume-The-WW** [comment]
Is there a way to fix this? I tried everything but nothing works

**Comment by DaHype** [comment]
Same Problem here. With v18.23.35 no Problem.

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
