### ISSUE TITLE
cast icon

### ISSUE THREAD

**Issue by zakislahb** [revanced-apks/build-apps#58]
hi,
thank you for your work and your efforts.
but I ask you if you can add cast icon in Revanced YouTube to be able to cast videos on TV,
and thank you for reading my comment.

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
