### ISSUE TITLE
YouTube Music Revanced is not playing album version tracks

### ISSUE THREAD

**Issue by AlexIs387** [revanced-apks/build-apps#59]
**Describe the bug**
It plays a musical video, as if it were the normal YouTube Music.

**To Reproduce**
1. Search an album.
2. Tap a song of the album.
3. A musical video is playing.

**Expected behavior**
Play the album version track instead a musical video.

**Smartphone (please complete the following information):**
 - Alcatel 3C
 - Android 7

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
