### ISSUE TITLE
The ''Mix Tab'' in YouTube revanced doesn't works

### ISSUE THREAD

**Issue by Mephisto116631** [revanced-apks/build-apps#66]
![IMG_20230824_155820](https://github.com/revanced-apks/build-apps/assets/123448378/8252cb42-60b7-435d-b199-4ef27f07c5e0)

**Describe the bug**
The ''Mix Tab'' in YouTube revanced doesn't charge

**To Reproduce**
1. Go to youtube home page
2. Click on Mix
3. See error

**Expected behavior**
Anything appears

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 11 T
 - OS: MIUI 14

**Additional context**

**DO NOT REPORT REVANCED BUGS IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**

**Comment by rabilrbl** [comment]
Please don't report any revanced bugs here.

Use revanced official [discord server](http://revanced.app/discord) or [telegram group](https://t.me/revanced_discussion) to report bugs.

Especially bugs on latest youtube builds.

All will be ignored.

Our job is to only compile revanced apps and distribute here, so that it's easy for end users like you.

We don't have control over anything else.

You can join our [discussion group](https://t.me/revanced_apks_chat) to chat and ask others about your problems.
